/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.awt.Image;
import java.io.File;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author nouri
 */
public class EditGroupPostWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditGroupPostWindow
     */
    GroupPost p;
    File f1 = null;
    Group group;

    public EditGroupPostWindow(GroupPost p, Group group) {
        initComponents();
        this.p = p;
        this.group = group;
        showgroupPost();
    }

    public void showgroupPost() {
        postText.setText(p.getContent());
        ImageIcon image = new ImageIcon(p.getImagePath());
        Image img = image.getImage();
        Image scaledImage = img.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        postLabel.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButton = new javax.swing.JButton();
        postLabel = new javax.swing.JLabel();
        postText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addimageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit post");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(51, 153, 255));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        postLabel.setBackground(new java.awt.Color(255, 255, 255));
        postLabel.setOpaque(true);

        postText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Content");

        addimageButton.setBackground(new java.awt.Color(51, 153, 255));
        addimageButton.setForeground(new java.awt.Color(255, 255, 255));
        addimageButton.setText("Change Image");
        addimageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addimageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(postText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addimageButton)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addimageButton)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(editButton))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
         String updatedContent = postText.getText();
        if (updatedContent.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Post content cannot be empty");
            return;
        }

        String updatedImagePath = (f1 != null) ? f1.getAbsolutePath() : "null";
        

        ArrayList<GroupPost> groupPosts = GroupPostDatabase.readGroupPosts();

        for (GroupPost post : groupPosts) 
        {
            if (post.getContentId() == p.getContentId()) {
                post.setContent(updatedContent);
                post.setImagePath(updatedImagePath);
            }
        }
        GroupPostDatabase.savePostsForGroup(groupPosts);

        JOptionPane.showMessageDialog(this, "Post updated successfully");

        AdminGroupProfile adminGroupProfile = new AdminGroupProfile(group);
        adminGroupProfile.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_editButtonActionPerformed

    
    private void postTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTextActionPerformed

    }//GEN-LAST:event_postTextActionPerformed

    private void addimageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addimageButtonActionPerformed
        JFileChooser file = new JFileChooser();
        int value = file.showOpenDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            f1 = file.getSelectedFile();
            GroupPostDatabase p = GroupPostDatabase.getInstance();
            ImageIcon scaledIcon = p.choosePostImage(f1, group);

            postLabel.setIcon(scaledIcon);
        }
    }//GEN-LAST:event_addimageButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        AdminGroupProfile adminGroupProfile = new AdminGroupProfile(group);
        adminGroupProfile.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addimageButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel postLabel;
    private javax.swing.JTextField postText;
    // End of variables declaration//GEN-END:variables
}
