/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nouri
 */
public class FriendRequestWindow extends javax.swing.JFrame {

    /**
     * Creates new form FriendRequestWindow
     */
    ArrayList<User> requests;
    ArrayList<User> users;
    ArrayList<User> friends;

    public FriendRequestWindow() {
        initComponents();
        requests = FriendRequestDatabase.readFriendRequests(Functionalities.currentUser.getUserId());
        loadFriendRequests();
        friends=FriendDatabase.readFriends(Functionalities.currentUser.getUserId());
        loadFriends();
        

    }

    DefaultListModel<String> listModel1;
    DefaultListModel<String> listModel2;
    DefaultListModel<String> listModel3;


    public void loadAllUsers() {
        listModel1 = new DefaultListModel<>();
        for (User user : users) {
            listModel1.addElement(user.getUsername());
        }
        friendRequestList.setModel(listModel1);
    }

    public void loadFriendRequests() {
        DefaultListModel<String> model = new DefaultListModel<>();

        for (User user : requests) {
            model.addElement(user.getUsername());
        }

        manageRequestsList.setModel(model);
    }

    public void loadSuggestedFriends() {
        DefaultListModel<String> model = new DefaultListModel<>();

    }
     public void loadFriends() {
        DefaultListModel<String> model = new DefaultListModel<>();

        for (User user : friends) {
            model.addElement(user.getUsername());
        }

        allFriends.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendFriendRequestButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageRequestsList = new javax.swing.JList<>();
        acceptButton = new javax.swing.JButton();
        requestSuggested = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendRequestList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        allFriends = new javax.swing.JList<>();
        blockButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Friend Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        sendFriendRequestButton.setText("Send friend request");
        sendFriendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFriendRequestButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(manageRequestsList);

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        requestSuggested.setText("Send friend request");
        requestSuggested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSuggestedActionPerformed(evt);
            }
        });

        jLabel1.setText("User name");

        jScrollPane2.setViewportView(friendRequestList);

        jLabel2.setText("Friend requests");

        jLabel3.setText("Suggested friends");

        jScrollPane3.setViewportView(jList3);

        jLabel4.setText("Friend List");

        jScrollPane4.setViewportView(allFriends);

        blockButton.setText("Block");
        blockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(requestSuggested))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(96, 96, 96))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addComponent(sendFriendRequestButton))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acceptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rejectButton))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendFriendRequestButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptButton)
                            .addComponent(rejectButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(requestSuggested)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blockButton)
                            .addComponent(removeButton))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendFriendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFriendRequestButtonActionPerformed
     ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = friendRequestList.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendRequestDatabase.saveFriendRequest(Functionalities.currentUser.getUserId(), u.getUserId()); //get static user
                }
            }
            listModel1 = (DefaultListModel<String>) friendRequestList.getModel();
            listModel1.removeElement(selectedRequest);
        }
    }//GEN-LAST:event_sendFriendRequestButtonActionPerformed


    private void blockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButtonActionPerformed
        ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = allFriends.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendRequestManagement.blockUser(u.getUserId());
                    FriendDatabase.removeFriendFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) allFriends.getModel();
            listModel2.removeElement(selectedRequest);
        }

    }//GEN-LAST:event_blockButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        users = FriendRequestManagement.search(usernameTextField.getText());
        loadAllUsers();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed

        ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = manageRequestsList.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendDatabase.saveFriends(u.getUserId());
                    FriendRequestDatabase.removeFriendRequestFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) manageRequestsList.getModel();
            listModel2.removeElement(selectedRequest);
        }


    }//GEN-LAST:event_acceptButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        ArrayList<User> everyone = UsersDatabase.readUsers();

    String selectedRequest = manageRequestsList.getSelectedValue();

    if (selectedRequest != null) {
        for (User user : everyone) {
            if (selectedRequest.equals(user.getUsername())) {
                FriendRequestDatabase.removeFriendRequestFromFile(user.getUserId());
                break;
            }
        }

        listModel2 = (DefaultListModel<String>) manageRequestsList.getModel();
        listModel2.removeElement(selectedRequest);
    }
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void requestSuggestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSuggestedActionPerformed

    }//GEN-LAST:event_requestSuggestedActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //newsfeed instead
        SignupLoginWindow signupLoginWindow = SignupLoginWindow.getInstance();
        signupLoginWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
         ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = allFriends.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendDatabase.removeFriendFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) allFriends.getModel();
            listModel2.removeElement(selectedRequest);
        }

    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FriendRequestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JList<String> allFriends;
    private javax.swing.JButton blockButton;
    private javax.swing.JList<String> friendRequestList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> manageRequestsList;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton requestSuggested;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton sendFriendRequestButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
