/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nouri
 */
public class FriendRequestWindow extends javax.swing.JFrame {

    /**
     * Creates new form FriendRequestWindow
     */
    ArrayList<User> requests;
    ArrayList<User> users;
    ArrayList<User> friends;
    ArrayList<User> suggestions;


    public FriendRequestWindow() {
        initComponents();
        requests = FriendRequestDatabase.readFriendRequests(Functionalities.currentUser.getUserId());
        loadFriendRequests();
        friends=FriendDatabase.readFriends(Functionalities.currentUser.getUserId());
        loadFriends();
        

    }

    DefaultListModel<String> listModel1;
    DefaultListModel<String> listModel2;
    DefaultListModel<String> listModel3;
    DefaultListModel<String> listModel4;


    public void loadAllUsers() {
        listModel1 = new DefaultListModel<>();
        ArrayList<User> updatedUsers = FriendRequestManagement.suggestFriends();

        for (User user : users) {
            listModel1.addElement(user.getUsername());
        }
        friendRequestList.setModel(listModel1);
    }

    public void loadFriendRequests() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (User user : requests) {
            model.addElement(user.getUsername());
        }

        manageRequestsList.setModel(model);
    }

    public void loadSuggestedFriends() {
         listModel1 = new DefaultListModel<>();
         ArrayList<User> suggested = FriendRequestManagement.suggestFriends();
        for (User user : suggested) {
            listModel1.addElement(user.getUsername());
        }
        suggestionsList.setModel(listModel1);
        

    }
     public void loadFriends() {
        DefaultListModel<String> model = new DefaultListModel<>();

        for (User user : friends) {
            model.addElement(user.getUsername());
        }

        allFriends.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendFriendRequestButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageRequestsList = new javax.swing.JList<>();
        acceptButton = new javax.swing.JButton();
        requestSuggested = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendRequestList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        suggestionsList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        allFriends = new javax.swing.JList<>();
        blockButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        showSuggestedButton = new javax.swing.JButton();
        showFriendListButton = new javax.swing.JButton();
        viewProfileButton = new javax.swing.JButton();
        viewProfileButton1 = new javax.swing.JButton();
        viewProfileButton2 = new javax.swing.JButton();
        blockButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Friend Management");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        sendFriendRequestButton.setBackground(new java.awt.Color(51, 153, 255));
        sendFriendRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        sendFriendRequestButton.setText("Send friend request");
        sendFriendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFriendRequestButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(manageRequestsList);

        acceptButton.setBackground(new java.awt.Color(51, 153, 255));
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        requestSuggested.setBackground(new java.awt.Color(51, 153, 255));
        requestSuggested.setForeground(new java.awt.Color(255, 255, 255));
        requestSuggested.setText("Send friend request");
        requestSuggested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSuggestedActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Search for Username");

        jScrollPane2.setViewportView(friendRequestList);

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Friend requests");

        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Suggested friends");

        jScrollPane3.setViewportView(suggestionsList);

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Friend List");

        jScrollPane4.setViewportView(allFriends);

        blockButton.setBackground(new java.awt.Color(51, 153, 255));
        blockButton.setForeground(new java.awt.Color(255, 255, 255));
        blockButton.setText("Block");
        blockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(51, 153, 255));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(51, 153, 255));
        rejectButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(51, 153, 255));
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        showSuggestedButton.setBackground(new java.awt.Color(51, 153, 255));
        showSuggestedButton.setForeground(new java.awt.Color(255, 255, 255));
        showSuggestedButton.setText("Show");
        showSuggestedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSuggestedButtonActionPerformed(evt);
            }
        });

        showFriendListButton.setBackground(new java.awt.Color(51, 153, 255));
        showFriendListButton.setForeground(new java.awt.Color(255, 255, 255));
        showFriendListButton.setText("Show");
        showFriendListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFriendListButtonActionPerformed(evt);
            }
        });

        viewProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        viewProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        viewProfileButton.setText("View Profile");
        viewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButtonActionPerformed(evt);
            }
        });

        viewProfileButton1.setBackground(new java.awt.Color(51, 153, 255));
        viewProfileButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewProfileButton1.setText("View Profile");
        viewProfileButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButton1ActionPerformed(evt);
            }
        });

        viewProfileButton2.setBackground(new java.awt.Color(51, 153, 255));
        viewProfileButton2.setForeground(new java.awt.Color(255, 255, 255));
        viewProfileButton2.setText("View Profile");
        viewProfileButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileButton2ActionPerformed(evt);
            }
        });

        blockButton1.setBackground(new java.awt.Color(51, 153, 255));
        blockButton1.setForeground(new java.awt.Color(255, 255, 255));
        blockButton1.setText("Block");
        blockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewProfileButton)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showSuggestedButton))))
                    .addComponent(requestSuggested)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendFriendRequestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blockButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(showFriendListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rejectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewProfileButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewProfileButton2)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptButton)
                            .addComponent(rejectButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProfileButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(showFriendListButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendFriendRequestButton)
                            .addComponent(blockButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showSuggestedButton)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestSuggested)
                    .addComponent(blockButton)
                    .addComponent(removeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewProfileButton2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendFriendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFriendRequestButtonActionPerformed
     ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = friendRequestList.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendRequestDatabase.saveFriendRequest(Functionalities.currentUser.getUserId(), u.getUserId()); //get static user
                }
            }
            listModel1 = (DefaultListModel<String>) friendRequestList.getModel();
            listModel1.removeElement(selectedRequest);
        }
    }//GEN-LAST:event_sendFriendRequestButtonActionPerformed


    private void blockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButtonActionPerformed
        ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = allFriends.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendRequestManagement.blockUser(u.getUserId());
                    FriendDatabase.removeFriendFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) allFriends.getModel();
            listModel2.removeElement(selectedRequest);
        }

    }//GEN-LAST:event_blockButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        users = FriendRequestManagement.search(usernameTextField.getText());
        loadAllUsers();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed

        ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = manageRequestsList.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendDatabase.saveFriends(u.getUserId());
                    FriendRequestDatabase.removeFriendRequestFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) manageRequestsList.getModel();
            listModel2.removeElement(selectedRequest);
        }


    }//GEN-LAST:event_acceptButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        ArrayList<User> everyone = UsersDatabase.readUsers();

    String selectedRequest = manageRequestsList.getSelectedValue();

    if (selectedRequest != null) {
        for (User user : everyone) {
            if (selectedRequest.equals(user.getUsername())) {
                FriendRequestDatabase.removeFriendRequestFromFile(user.getUserId());
                break;
            }
        }

        listModel2 = (DefaultListModel<String>) manageRequestsList.getModel();
        listModel2.removeElement(selectedRequest);
    }
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void requestSuggestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSuggestedActionPerformed
      ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = suggestionsList.getSelectedValue();
        if (selectedRequest != null) 
            {
            for (User u : everyone) 
            {
                if (selectedRequest.equals(u.getUsername())) 
                {
                    FriendRequestDatabase.saveFriendRequest(Functionalities.currentUser.getUserId(), u.getUserId()); //get static user
                }
            }
            listModel4 = (DefaultListModel<String>) suggestionsList.getModel();
            listModel4.removeElement(selectedRequest);
        }
        
    }//GEN-LAST:event_requestSuggestedActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //newsfeed opens
        NewsFeed newsfeed = new NewsFeed();
        newsfeed.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
         ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = allFriends.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendDatabase.removeFriendFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) allFriends.getModel();
            listModel2.removeElement(selectedRequest);
        }

    }//GEN-LAST:event_removeButtonActionPerformed

    private void showSuggestedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSuggestedButtonActionPerformed
        // TODO add your handling code here:
         suggestions = FriendRequestManagement.suggestFriends();
         loadSuggestedFriends();
    }//GEN-LAST:event_showSuggestedButtonActionPerformed

    private void showFriendListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFriendListButtonActionPerformed
        // TODO add your handling code here:
        friends = FriendDatabase.readFriends(Functionalities.currentUser.getUserId());
         loadFriends();
    }//GEN-LAST:event_showFriendListButtonActionPerformed

    private void viewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButtonActionPerformed
       ArrayList<User> everyone = new ArrayList<>(UsersDatabase.readUsers());
         ViewFriendProfileWindow view;

        String selectedUser = friendRequestList.getSelectedValue();
        if (selectedUser != null) {
            for (User u : everyone) {
                if(selectedUser.equals(u.getUsername()))
                {   view=new ViewFriendProfileWindow(u.getUsername());
                  view.setVisible(true);
                }
            } 
    }                                                 
   else{
            JOptionPane.showMessageDialog(this, "Please Choose a user");
            
            
        }
    }//GEN-LAST:event_viewProfileButtonActionPerformed

    private void viewProfileButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButton1ActionPerformed
        ArrayList<User> everyone = new ArrayList<>(UsersDatabase.readUsers());
ViewFriendProfileWindow view;

String selectedUser = manageRequestsList.getSelectedValue();
if (selectedUser != null) {
    for (User u : everyone) {
        if (selectedUser.equals(u.getUsername())) {
            view = new ViewFriendProfileWindow(u.getUsername());
            view.setVisible(true);
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Please Choose a user");
}
    }//GEN-LAST:event_viewProfileButton1ActionPerformed

    private void viewProfileButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileButton2ActionPerformed
        ArrayList<User> everyone = new ArrayList<>(UsersDatabase.readUsers());
        ViewFriendProfileWindow view;

       String selectedUser = allFriends.getSelectedValue();
if (selectedUser != null) {
    for (User u : everyone) {
        if (selectedUser.equals(u.getUsername())) {
            view = new ViewFriendProfileWindow(u.getUsername());
            view.setVisible(true);
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Please Choose a user");
}
    }//GEN-LAST:event_viewProfileButton2ActionPerformed

    private void blockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButton1ActionPerformed
        ArrayList<User> everyone = UsersDatabase.readUsers();

        String selectedRequest = friendRequestList.getSelectedValue();
        if (selectedRequest != null) {
            for (User u : everyone) {
                if (selectedRequest.equals(u.getUsername())) {
                    FriendRequestManagement.blockUser(u.getUserId());
                   // FriendDatabase.removeFriendFromFile(u.getUserId());
                }
            }
            listModel2 = (DefaultListModel<String>) friendRequestList.getModel();
            listModel2.removeElement(selectedRequest);
        }
    }//GEN-LAST:event_blockButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JList<String> allFriends;
    private javax.swing.JButton blockButton;
    private javax.swing.JButton blockButton1;
    private javax.swing.JList<String> friendRequestList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> manageRequestsList;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton requestSuggested;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton sendFriendRequestButton;
    private javax.swing.JButton showFriendListButton;
    private javax.swing.JButton showSuggestedButton;
    private javax.swing.JList<String> suggestionsList;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JButton viewProfileButton;
    private javax.swing.JButton viewProfileButton1;
    private javax.swing.JButton viewProfileButton2;
    // End of variables declaration//GEN-END:variables
}
