/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nouri
 */
public class GroupManagementWindow extends javax.swing.JFrame {

    ArrayList<Object> groupsAndUsers;
    ArrayList<Group> groups;

    /**
     * Creates new form GroupManagementWindow
     */
    public GroupManagementWindow() {
        initComponents();
        groups = GroupDatabase.readGroupsForUser(Functionalities.currentUser.getUserId());
        System.out.println("Groups to be loaded: " + groups.size());
        for (Group group : groups) {
            System.out.println("Group: " + group.getName());
        }

        loadAllGroups();
        //loadAllSuggestedGroups();
        joinGroupButton.setVisible(false);
        leaveGroupButton.setVisible(false);
        viewGroupButton.setVisible(false);

    }
    DefaultListModel<String> listModel1;
    DefaultListModel<String> listModel2;
    DefaultListModel<String> listModel3;
    

    public void loadAllUsers() {
        listModel1 = new DefaultListModel<>();
        for (Object obj : groupsAndUsers) {
            if (obj instanceof User) {
                listModel1.addElement(((User) obj).getUsername() + " (user) ");
            } else if (obj instanceof Group) {
                listModel1.addElement(((Group) obj).getName() + " (group) ");
            }
        }
        groupsAndUsersList.setModel(listModel1);
    }

    public void loadAllGroups() {
        listModel2 = new DefaultListModel<>();

        for (Group group : groups) {
            listModel2.addElement(group.getName());
        }

        groupsList.setModel(listModel2);

    }
    /*public void loadAllSuggestedGroups() {
        listModel3 = new DefaultListModel<>();
        ArrayList<Group> suggested = GroupDatabase.suggestGroups();

        for (Group group : suggested) {
            listModel3.addElement(group.getName());
        }

        groupsSuggestionsList.setModel(listModel3);

    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        groupsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        joinGroupButton = new javax.swing.JButton();
        leaveGroupButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupsAndUsersList = new javax.swing.JList<>();
        searchGroupButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        viewGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Groups");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane2.setViewportView(groupsList);

        jLabel2.setText("Groups");

        joinGroupButton.setText("Join Group");
        joinGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGroupButtonActionPerformed(evt);
            }
        });

        leaveGroupButton.setText("Leave Group");
        leaveGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveGroupButtonActionPerformed(evt);
            }
        });

        groupsAndUsersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupsAndUsersListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(groupsAndUsersList);

        searchGroupButton.setText("Search");
        searchGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGroupButtonActionPerformed(evt);
            }
        });

        searchTextField.setText("Search Users and Groups");

        viewGroupButton.setText("View Group");
        viewGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leaveGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(joinGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(searchTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGroupButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joinGroupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leaveGroupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewGroupButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGroupButtonActionPerformed
        ArrayList<Group> allGroups = GroupDatabase.readGroups();

        String selectedRequest = groupsAndUsersList.getSelectedValue();

        boolean found = false;

        if (selectedRequest != null) {
            for (Group g : allGroups) {
                if (selectedRequest.equals(g.getName() + " (group) ")) {

                    if (Functionalities.currentUser.getUsername().equals(g.getPrimaryAdmin())) {
                        AdminGroupProfile adminGroupProfile = new AdminGroupProfile(g);
                        adminGroupProfile.setVisible(true);
                        this.setVisible(false);
                        found = true;
                        break;
                    } else {
                        for (User user : g.getAdmins()) {
                            if (user.getUserId() == Functionalities.currentUser.getUserId()) {
                                AdminGroupProfile adminGroupProfile = new AdminGroupProfile(g);
                                adminGroupProfile.setVisible(true);
                                this.setVisible(false);
                                found = true;
                                break;
                            }
                        }

                        for (User user : g.getMembers()) {
                            if (user.getUserId() == Functionalities.currentUser.getUserId()) {
                                System.out.println("member");
                                UserGroupProfile userGroupProfile = new UserGroupProfile(g);
                                userGroupProfile.setVisible(true);
                                this.setVisible(false);
                                found = true;
                                break;
                            }
                        }
                    }
                    if (found) {
                        break;
                    }
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "You are not a member of this group", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please choose an element", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_viewGroupButtonActionPerformed

    private void searchGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGroupButtonActionPerformed
        groupsAndUsers = GroupEditing.search(nameTextField.getText());
        loadAllUsers();
    }//GEN-LAST:event_searchGroupButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        NewsFeed newsFeed = new NewsFeed();
        newsFeed.setVisible(true);

    }//GEN-LAST:event_formWindowClosed

    private void joinGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGroupButtonActionPerformed
        ArrayList<Group> allGroups = GroupDatabase.readGroups();

        String selectedRequest = groupsAndUsersList.getSelectedValue();

        boolean found = false;

        if (selectedRequest != null) {
            for (Group g : allGroups) {
                if (selectedRequest.equals(g.getName() + " (group) ")) {

                    if (Functionalities.currentUser.getUsername().equals(g.getPrimaryAdmin())) {
                        JOptionPane.showMessageDialog(this, "You are already a member", "Error", JOptionPane.ERROR_MESSAGE);
                        found = true;
                        break;
                    } else {
                        for (User user : g.getAdmins()) {
                            if (user.getUserId() == Functionalities.currentUser.getUserId()) {
                                JOptionPane.showMessageDialog(this, "You are already a member", "Error", JOptionPane.ERROR_MESSAGE);
                                found = true;
                                break;
                            }
                        }

                        for (User user : g.getMembers()) {
                            if (user.getUserId() == Functionalities.currentUser.getUserId()) {
                                JOptionPane.showMessageDialog(this, "You are already a member", "Error", JOptionPane.ERROR_MESSAGE);
                                found = true;
                                break;
                            }
                        }
                    }
                    if (found) {
                        break;
                    }
                    MembershipRequestDatabase.saveMembershipRequest(Functionalities.currentUser.getUserId(), g.getGroupId());
                    GroupLeftDatabase.removeGroupLeft(Functionalities.currentUser.getUserId(), g.getGroupId());
                    listModel1 = (DefaultListModel<String>) groupsAndUsersList.getModel();
                    listModel1.removeElement(selectedRequest);
                    groupsAndUsersList.setModel(listModel1);
                    //groupsAndUsersList.updateUI();
                    //groupsAndUsersList.clearSelection();

                    break;

                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please choose an element", "Error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_joinGroupButtonActionPerformed

    private void leaveGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveGroupButtonActionPerformed
        ArrayList<Group> allGroups = GroupDatabase.readGroups();

        String selectedRequest = groupsAndUsersList.getSelectedValue();

        if (selectedRequest != null) {
            for (Group g : allGroups) {
                if (selectedRequest.equals(g.getName() + " (group) ")) {
                    GroupDatabase.leaveGroup(g.getGroupId());
                    return;

                    // Clear selection to maintain a clean view
                    //groupsAndUsersList.clearSelection();
                }
            }


        }    }//GEN-LAST:event_leaveGroupButtonActionPerformed

    private void groupsAndUsersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupsAndUsersListValueChanged
        String selectedRequest = groupsAndUsersList.getSelectedValue();
        if (selectedRequest.endsWith(" (group) ")) {
            joinGroupButton.setVisible(true);
            leaveGroupButton.setVisible(true);
            viewGroupButton.setVisible(true);
        } else {
            joinGroupButton.setVisible(false);
            leaveGroupButton.setVisible(false);
            viewGroupButton.setVisible(false);
        }
    }//GEN-LAST:event_groupsAndUsersListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupManagementWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> groupsAndUsersList;
    private javax.swing.JList<String> groupsList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton joinGroupButton;
    private javax.swing.JButton leaveGroupButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton searchGroupButton;
    private javax.swing.JLabel searchTextField;
    private javax.swing.JButton viewGroupButton;
    // End of variables declaration//GEN-END:variables
}
