/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author X1
 */
public class UserProfile extends javax.swing.JFrame {

    String Bio;

    /**
     * Creates new form UserProfile
     */   
    ArrayList<Post> p ;
    ArrayList<User> friends;
    ArrayList<Story> stories;
    ArrayList<User> users;

    public UserProfile() {
        initComponents();
        //get lists of posts and friends of current user
        p= PostDatabase.readPostsforUser(Functionalities.currentUser.getUserId());
        friends=FriendDatabase.readFriends(Functionalities.currentUser.getUserId());
        stories=StoryDatabase.readStoriesforUser(Functionalities.currentUser.getUserId());
        users=UsersDatabase.readUsers();
        LoadPosts();
         LoadFriends();
         LoadStories();
         Loadpfp();
         LoadcoverPhoto();
         LoadBio();
    }

    public void LoadPosts() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        for (Post post : p) {
            listModel.addElement(post.getContent());
        }
        postsList.setModel(listModel);
    }

    public void LoadFriends() {
        //view friends in FriendList
        DefaultListModel<String> listModel = new DefaultListModel<>();

        for (User friend : friends) {
            listModel.addElement(friend.getUsername());
        }
        FriendsList.setModel(listModel);

    }
     public void LoadStories() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        StoryDatabase.deleteStories();
        for (Story story : stories) {
            listModel.addElement(story.getContent());
            
        }
        storiesList.setModel(listModel);
    }
     
     public void Loadpfp()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==Functionalities.currentUser.getUserId())
             {
                  filepath=users.get(i).getProfilePicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon profilePicture = new ImageIcon(filepath);
    Image pfp = profilePicture.getImage();
    Image scaledPFP = pfp.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    pfpJLabel.setIcon(scaledIcon);
         }
         
         
     }
     public void LoadcoverPhoto()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==Functionalities.currentUser.getUserId())
             {
                  filepath=users.get(i).getCoverPicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon coverPhoto = new ImageIcon(filepath);
    Image cover = coverPhoto.getImage();
    Image scaledPFP = cover.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    coverJLabel.setIcon(scaledIcon);
         }
         
         
     }
     
     public void LoadBio()
     {
         String newBio=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==Functionalities.currentUser.getUserId())
             {
                  newBio=users.get(i).getBio();
             }
         }
         
         bioText.setText(newBio);
         
         
     }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        profilepicButton = new javax.swing.JButton();
        coverpicButton = new javax.swing.JButton();
        pfpJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bioText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendsList = new javax.swing.JList<>();
        viewPost = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postsList = new javax.swing.JList<>();
        changeBio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        storiesList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        viewStories = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("user profile");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        coverJLabel.setBackground(new java.awt.Color(255, 255, 255));
        coverJLabel.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        profilepicButton.setBackground(new java.awt.Color(51, 153, 255));
        profilepicButton.setText("Change Profile Picture");
        profilepicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilepicButtonActionPerformed(evt);
            }
        });

        coverpicButton.setBackground(new java.awt.Color(51, 153, 255));
        coverpicButton.setText("Change Cover Photo");
        coverpicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coverpicButtonActionPerformed(evt);
            }
        });

        pfpJLabel.setBackground(new java.awt.Color(255, 255, 255));
        pfpJLabel.setOpaque(true);

        jLabel1.setText("Bio");

        bioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Posts");

        jScrollPane1.setViewportView(FriendsList);

        viewPost.setBackground(new java.awt.Color(51, 153, 255));
        viewPost.setText("View Post");
        viewPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPostActionPerformed(evt);
            }
        });

        jLabel3.setText("Friends List");

        jScrollPane2.setViewportView(postsList);

        changeBio.setBackground(new java.awt.Color(51, 153, 255));
        changeBio.setText("change Bio");
        changeBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBioActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(storiesList);

        jLabel4.setText("Stories");

        viewStories.setBackground(new java.awt.Color(51, 153, 255));
        viewStories.setText("View Story");
        viewStories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(profilepicButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(pfpJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(coverpicButton)
                                .addGap(50, 50, 50))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bioText, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(changeBio)))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(116, 116, 116)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(viewPost)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewStories)
                        .addGap(18, 18, 18)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfpJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilepicButton)
                    .addComponent(coverpicButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bioText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(changeBio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewStories))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewPost))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coverpicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coverpicButtonActionPerformed
        
        //change coverphoto of current user
        JFileChooser file = new JFileChooser();
        int value=file.showOpenDialog(this);
        if(value==JFileChooser.APPROVE_OPTION)
        { File f = file.getSelectedFile();
        
        ProfileEditing p = new ProfileEditing();
        ImageIcon scaledIcon = p.changeCoverPhoto(f);

        coverJLabel.setIcon(scaledIcon);
        }
    }//GEN-LAST:event_coverpicButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //change password of currentuser
        String password = JOptionPane.showInputDialog(this, "change password");
     
        ProfileEditing pf = new ProfileEditing();
        if (Functionalities.isValidPassword(password)) {
            pf.changePassword(password);
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a valid password", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioTextActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_bioTextActionPerformed

    private void profilepicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilepicButtonActionPerformed
        // TODO add your handling code here:
         //change profile picture of current user
        JFileChooser file = new JFileChooser();
        int value=file.showOpenDialog(this);
        if(value==JFileChooser.APPROVE_OPTION)
        { File f = file.getSelectedFile();
       
        ProfileEditing p = new ProfileEditing();
        ImageIcon scaledIcon = p.changePFP(f);
        pfpJLabel.setIcon(scaledIcon);
        }

    }//GEN-LAST:event_profilepicButtonActionPerformed

    private void viewPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPostActionPerformed
        // TODO add your handling code here:
        //view post details of a choosen post
        int index = postsList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose post");
        } else {
            Post post = p.get(index);
            this.setVisible(false);
            ViewPosts view = new ViewPosts(post);
            view.setVisible(true);
        }


    }//GEN-LAST:event_viewPostActionPerformed

    private void changeBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBioActionPerformed
        // TODO add your handling code here:
        //change bio of current user
         Bio= JOptionPane.showInputDialog("Enter Bio.");
        ProfileEditing p = new ProfileEditing();
        p.changeBio(Bio);
        bioText.setText(Bio);
   
        
    }//GEN-LAST:event_changeBioActionPerformed

    private void viewStoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStoriesActionPerformed
        int index = storiesList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose story");
        } else {
            Story story = stories.get(index);
            this.setVisible(false);
            ViewStories view = new ViewStories(story);
            view.setVisible(true);
        }
    }//GEN-LAST:event_viewStoriesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        NewsFeed newsfeed = new NewsFeed();
        newsfeed.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> FriendsList;
    private javax.swing.JTextField bioText;
    private javax.swing.JButton changeBio;
    private javax.swing.JLabel coverJLabel;
    private javax.swing.JButton coverpicButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel pfpJLabel;
    private javax.swing.JList<String> postsList;
    private javax.swing.JButton profilepicButton;
    private javax.swing.JList<String> storiesList;
    private javax.swing.JButton viewPost;
    private javax.swing.JButton viewStories;
    // End of variables declaration//GEN-END:variables
}
