/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class ViewFriendProfileWindow extends javax.swing.JFrame {
ArrayList<Post> posts ;
    ArrayList<User> friends;
    ArrayList<Story> stories;
    ArrayList<User> users;
    User viewedUser;
    /**
     * Creates new form ViewFriendProfileWindow
     */
    public ViewFriendProfileWindow(String username) {
        initComponents();
        this.viewedUser=Functionalities.getUser(username);
        posts= PostDatabase.readPostsforUser(viewedUser.getUserId());
        friends=FriendDatabase.readFriends(viewedUser.getUserId());
        stories=StoryDatabase.readStoriesforUser(viewedUser.getUserId());
        users=UsersDatabase.readUsers();
         LoadPosts();
         LoadFriends();
         LoadStories();
         Loadpfp();
         LoadcoverPhoto();
         LoadBio();
         LoadName();
    }
     public void LoadName()
     {   
             String Name=viewedUser.getUsername();
             NameLabel.setText(Name);
}
    
    public void LoadPosts() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        for (Post post : posts) {
            listModel.addElement(post.getContent());
        }
         postsList.setModel(listModel);
    }

    public void LoadFriends() {
        //view friends in FriendList
        DefaultListModel<String> listModel = new DefaultListModel<>();

        for (User friend : friends) {
            listModel.addElement(friend.getUsername() + " ("+friend.getStatus()+") ");
        }
         FriendsList.setModel(listModel);

    }
     public void LoadStories() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        StoryDatabase.deleteStories();
        for (Story story : stories) {
            listModel.addElement(story.getContent());
            
        }
        storiesList.setModel(listModel);
        
    }
     
     public void Loadpfp()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  filepath=users.get(i).getProfilePicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon profilePicture = new ImageIcon(filepath);
    Image pfp = profilePicture.getImage();
    Image scaledPFP = pfp.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    pfpLabel.setIcon(scaledIcon);
         }
         
         
     }
     public void LoadcoverPhoto()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  filepath=users.get(i).getCoverPicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon coverPhoto = new ImageIcon(filepath);
    Image cover = coverPhoto.getImage();
    Image scaledPFP = cover.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    CoverLabel.setIcon(scaledIcon);
         }
         
         
     }
     
     public void LoadBio()
     {
         String newBio=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  newBio=users.get(i).getBio();
             }
         }
         if(newBio.equals("null"))
         {
             BioText.setText("");
         }
         else{
         BioText.setText(newBio);
         }
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoverLabel = new javax.swing.JLabel();
        BioText = new javax.swing.JLabel();
        pfpLabel = new javax.swing.JLabel();
        BioLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storiesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        FriendsList = new javax.swing.JList<>();
        viewStoriesButton = new javax.swing.JButton();
        viewPostButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CoverLabel.setBackground(new java.awt.Color(255, 255, 255));
        CoverLabel.setOpaque(true);

        BioText.setBackground(new java.awt.Color(255, 255, 255));
        BioText.setOpaque(true);

        pfpLabel.setBackground(new java.awt.Color(255, 255, 255));
        pfpLabel.setOpaque(true);

        BioLabel.setText("Bio");

        NameLabel.setOpaque(true);

        jScrollPane1.setViewportView(storiesList);

        jLabel2.setText("Posts");

        jLabel3.setText("Stories");

        jLabel4.setText("Friends List");

        jScrollPane2.setViewportView(postsList);

        jScrollPane3.setViewportView(FriendsList);

        viewStoriesButton.setBackground(new java.awt.Color(51, 153, 255));
        viewStoriesButton.setForeground(new java.awt.Color(255, 255, 255));
        viewStoriesButton.setText("View stories");
        viewStoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStoriesButtonActionPerformed(evt);
            }
        });

        viewPostButton.setBackground(new java.awt.Color(51, 153, 255));
        viewPostButton.setForeground(new java.awt.Color(255, 255, 255));
        viewPostButton.setText("View Post");
        viewPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPostButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(viewPostButton)
                        .addGap(107, 107, 107)
                        .addComponent(viewStoriesButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel3))
                            .addComponent(BioText, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pfpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(198, 198, 198)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(pfpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BioLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BioText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewStoriesButton)
                            .addComponent(viewPostButton))
                        .addGap(0, 16, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStoriesButtonActionPerformed
        // TODO add your handling code here:
        int index = storiesList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose story");
        } else {
            Story story = stories.get(index);
            this.setVisible(false);
            ViewStories view = new ViewStories(story);
            view.setVisible(true);
        }
    }//GEN-LAST:event_viewStoriesButtonActionPerformed

    private void viewPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPostButtonActionPerformed
        // TODO add your handling code here:
          //view post details of a choosen post
        int index = postsList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose post");
        } else {
            Post post = posts.get(index);
            this.setVisible(false);
            ViewPosts view = new ViewPosts(post);
            view.setVisible(true);
        }
    }//GEN-LAST:event_viewPostButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BioLabel;
    private javax.swing.JLabel BioText;
    private javax.swing.JLabel CoverLabel;
    private javax.swing.JList<String> FriendsList;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel pfpLabel;
    private javax.swing.JList<String> postsList;
    private javax.swing.JList<String> storiesList;
    private javax.swing.JButton viewPostButton;
    private javax.swing.JButton viewStoriesButton;
    // End of variables declaration//GEN-END:variables
}
