/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author X1
 */
public class ViewFriendProfileWindow extends javax.swing.JFrame {

     ArrayList<Post> posts ;
    ArrayList<User> friends;
    ArrayList<Story> stories;
    ArrayList<User> users;
    User viewedUser;
    
    /**
     * Creates new form ViewFriendProfileWindow
     */
    public ViewFriendProfileWindow(String username) {
        initComponents();
        this.viewedUser=Functionalities.getUser(username);
        posts= PostDatabase.readPostsforUser(viewedUser.getUserId());
        friends=FriendDatabase.readFriends(viewedUser.getUserId());
        stories=StoryDatabase.readStoriesforUser(viewedUser.getUserId());
        users=UsersDatabase.readUsers();
         LoadPosts();
         LoadFriends();
         LoadStories();
         Loadpfp();
         LoadcoverPhoto();
         LoadBio();
         LoadName();
        
    }
    
    public void LoadName()
     {   
             String Name=viewedUser.getUsername();
             NameLabel.setText(Name);
}
    
    public void LoadPosts() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        for (Post post : posts) {
            listModel.addElement(post.getContent());
        }
         postsList.setModel(listModel);
    }

    public void LoadFriends() {
        //view friends in FriendList
        DefaultListModel<String> listModel = new DefaultListModel<>();

        for (User friend : friends) {
            listModel.addElement(friend.getUsername() + " ("+friend.getStatus()+") ");
        }
         FriendsList.setModel(listModel);

    }
     public void LoadStories() {
        //view posts in postsList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        StoryDatabase.deleteStories();
        for (Story story : stories) {
            listModel.addElement(story.getContent());
            
        }
        storiesList.setModel(listModel);
        
    }
     
     public void Loadpfp()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  filepath=users.get(i).getProfilePicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon profilePicture = new ImageIcon(filepath);
    Image pfp = profilePicture.getImage();
    Image scaledPFP = pfp.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    pfpJLabel.setIcon(scaledIcon);
         }
         
         
     }
     public void LoadcoverPhoto()
     {
         String filepath=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  filepath=users.get(i).getCoverPicture();
             }
         }
         
         if(filepath!=null)
         {
           ImageIcon coverPhoto = new ImageIcon(filepath);
    Image cover = coverPhoto.getImage();
    Image scaledPFP = cover.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledPFP);
    coverJLabel.setIcon(scaledIcon);
         }
         
         
     }
     
     public void LoadBio()
     {
         String newBio=null;
         for(int i=0;i<users.size();i++)
         {
             if(users.get(i).getUserId()==viewedUser.getUserId())
             {
                  newBio=users.get(i).getBio();
             }
         }
         if(newBio.equals("null"))
         {
             bioText.setText("");
         }
         else{
         bioText.setText(newBio);
         }
         
     }
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfpJLabel = new javax.swing.JLabel();
        coverJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bioText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        postsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        storiesList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendsList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        viewStories = new javax.swing.JButton();
        viewPost = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile");

        pfpJLabel.setBackground(new java.awt.Color(255, 255, 255));
        pfpJLabel.setOpaque(true);

        coverJLabel.setBackground(new java.awt.Color(255, 255, 255));
        coverJLabel.setOpaque(true);

        jLabel1.setText("Bio");

        bioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioTextActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(postsList);

        jScrollPane3.setViewportView(storiesList);

        jLabel4.setText("Stories");

        jLabel2.setText("Posts");

        jScrollPane1.setViewportView(FriendsList);

        jLabel3.setText("Friends List");

        viewStories.setBackground(new java.awt.Color(51, 153, 255));
        viewStories.setForeground(new java.awt.Color(255, 255, 255));
        viewStories.setText("View Story");
        viewStories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStoriesActionPerformed(evt);
            }
        });

        viewPost.setBackground(new java.awt.Color(51, 153, 255));
        viewPost.setForeground(new java.awt.Color(255, 255, 255));
        viewPost.setText("View Post");
        viewPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPostActionPerformed(evt);
            }
        });

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pfpJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bioText, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)
                                .addComponent(jLabel4)
                                .addGap(121, 121, 121)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(viewPost)
                        .addGap(147, 147, 147)
                        .addComponent(viewStories))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfpJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bioText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPost)
                    .addComponent(viewStories))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bioTextActionPerformed

    private void viewStoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStoriesActionPerformed
        int index = storiesList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose story");
        } else {
            Story story = stories.get(index);
            this.setVisible(false);
            ViewStories view = new ViewStories(story);
            view.setVisible(true);
        }
    }//GEN-LAST:event_viewStoriesActionPerformed

    private void viewPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPostActionPerformed
        // TODO add your handling code here:
        //view post details of a choosen post
        int index = postsList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose post");
        } else {
            Post post = posts.get(index);
            this.setVisible(false);
            ViewPosts view = new ViewPosts(post);
            view.setVisible(true);
        }

    }//GEN-LAST:event_viewPostActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> FriendsList;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField bioText;
    private javax.swing.JLabel coverJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel pfpJLabel;
    private javax.swing.JList<String> postsList;
    private javax.swing.JList<String> storiesList;
    private javax.swing.JButton viewPost;
    private javax.swing.JButton viewStories;
    // End of variables declaration//GEN-END:variables
}
