/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connecthub;

import com.mycompany.connecthub.Functionalities;
import com.mycompany.connecthub.User;
import com.mycompany.connecthub.UserGroupProfile;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author karen
 */

public class ViewGroupPosts extends javax.swing.JFrame {

    GroupPost p;
    Group group;
    /**
     * Creates new form ViewGroupPosts
     */
    public ViewGroupPosts(GroupPost p, Group group) {
        initComponents();
        this.p=p;
        this.group=group;
        showgroupPost();

    }
    
    public void showgroupPost() {
        viewContent.setText(p.getContent());
        viewDate.setText(p.getTimeStamp().toString());
        ImageIcon image = new ImageIcon(p.getImagePath());
        Image img = image.getImage();
        Image scaledImage = img.getScaledInstance(300, 200, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        viewPhoto.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPhoto = new javax.swing.JLabel();
        viewDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        viewContent = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Post");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        viewPhoto.setBackground(new java.awt.Color(255, 255, 255));
        viewPhoto.setOpaque(true);

        viewDate.setBackground(new java.awt.Color(255, 255, 255));
        viewDate.setOpaque(true);

        jLabel1.setText("Content");

        viewContent.setBackground(new java.awt.Color(255, 255, 255));
        viewContent.setOpaque(true);

        jLabel2.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(viewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(viewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewContent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(viewPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            User currentUser = Functionalities.currentUser; 
            int groupId = group.getGroupId(); 

            String jsonLines = new String(Files.readAllBytes(Paths.get("groups.json")));
            JSONArray groupsArray = new JSONArray(jsonLines);

            for (int i = 0; i < groupsArray.length(); i++) {
                JSONObject groupJson = groupsArray.getJSONObject(i);
                if (groupJson.getInt("groupId") == groupId) {
                    String primaryAdmin = groupJson.getString("primaryAdmin");
                    JSONArray adminsArray = groupJson.getJSONArray("admins");
                    JSONArray membersArray = groupJson.getJSONArray("members");

                    if (primaryAdmin.equals(currentUser.getUsername())) {
                        AdminGroupProfile adminWindow = new AdminGroupProfile(group);
                        adminWindow.setVisible(true);
                    } else if (isUserInList(currentUser.getUsername(), adminsArray)) {
                        AdminGroupProfile adminWindow = new AdminGroupProfile(group);
                        adminWindow.setVisible(true);
                    } else if (isUserInList(currentUser.getUsername(), membersArray)) {
                        UserGroupProfile userWindow = new UserGroupProfile(group);
                        userWindow.setVisible(true);
                    }
                    break; 
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while loading the group details.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean isUserInList(String username, JSONArray jsonArray) {
        for (int i = 0; i < jsonArray.length(); i++) {
            if (jsonArray.getString(i).equals(username)) {
                return true;
            }
        }
        return false;
    
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel viewContent;
    private javax.swing.JLabel viewDate;
    private javax.swing.JLabel viewPhoto;
    // End of variables declaration//GEN-END:variables
}
